# Function to display help
mybash_help() {
    echo "MyBash Utilities:"
    echo "-----------------"
    echo "Shortcuts (Direct Commands):"
    echo "  cpwd          - Copy current directory path to clipboard"
    echo "  largefiles    - List the 10 largest files in the current directory"
    echo "  opendir       - Open the current directory in Finder"
    echo "  mkcd          - Create a directory and navigate into it"
    echo "  myip          - Display the Wi-Fi IP address"
    echo "  bkm           - Bookmark directories (add, list, remove)"
    echo "                  Usage: bkm <name> to navigate to a bookmarked directory"
    echo "                  Examples:"
    echo "                    bkm add proj ~/Projects/my_project"
    echo "                    bkm proj"
    echo "                    bkm list"
    echo "                    bkm remove proj"
    echo "  cmd           - Bookmark commands (add, list, remove)"
    echo "                  Usage: cmd <name> to execute a bookmarked command"
    echo "                  Examples:"
    echo "                    cmd add gs 'git status'"
    echo "                    cmd gs"
    echo "                    cmd list"
    echo "                    cmd remove gs"
    echo ""
    echo "MyBash Commands (Use 'mybash' or 'mb'):"
    echo "  export        - Export bookmarks and commands to ~/Documents/mybash/export"
    echo "  import        - Import bookmarks and commands from ~/Documents/mybash/export"
    echo "  empty         - Empty a file after confirmation"
    echo "                  Usage: mybash empty <filename>"
    echo "  clean         - Clear the content of a file after confirmation"
    echo "                  Usage: mybash clean <filename>"
    echo ""
    echo "Dependencies:"
    echo "  - jq: Required for exporting and importing data in JSON format."
    echo "        Install via Homebrew (macOS): brew install jq"
    echo "        Install via apt (Linux): sudo apt install jq"
    echo "        Install via yum (Linux): sudo yum install jq"
    echo ""
    echo "Usage:"
    echo "  mybash --help - Show this help message"
    echo "  mb --help     - Same as above (alias for 'mybash')"
}